"""add symptom_reports table

Revision ID: 2e9d19cf5526
Revises: 
Create Date: 2026-04-07 01:02:41.695395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e9d19cf5526'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptom_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('primary_symptom', sa.String(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('associated_symptoms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('medication_taken', sa.String(), nullable=True),
    sa.Column('urgency_level', sa.String(), nullable=True),
    sa.Column('raw_transcript', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_reports_id'), 'symptom_reports', ['id'], unique=False)
    op.drop_table('triage_records')
    op.drop_table('patients')
    op.drop_index('ix_users_employee_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_employee_id', 'users', ['employee_id'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('village', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pregnant', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('abha_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='patients_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='patients_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('triage_records',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('patient_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('caller_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('call_sid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recording_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transcript', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transcript_english', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transcript_hindi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transcript_odia', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('symptoms', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sickle_cell_risk', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('brief', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reviewed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='triage_records_patient_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='triage_records_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='triage_records_pkey')
    )
    op.drop_index(op.f('ix_symptom_reports_id'), table_name='symptom_reports')
    op.drop_table('symptom_reports')
    # ### end Alembic commands ###
