"""add asha_worker_id to triage_records

Revision ID: a2f77d6b07c6
Revises: 7995cda64aed
Create Date: 2026-04-08 15:00:42.059688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2f77d6b07c6'
down_revision: Union[str, None] = '7995cda64aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_symptom_reports_id', table_name='symptom_reports')
    op.drop_table('symptom_reports')
    op.drop_index('ix_users_employee_id', table_name='users')
    op.drop_table('users')
    op.drop_table('patients')
    op.alter_column('triage_records', 'transcript',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('triage_records', 'transcript_english',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('triage_records', 'transcript_hindi',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('triage_records', 'transcript_odia',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('triage_records', 'brief',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint('triage_records_patient_id_fkey', 'triage_records', type_='foreignkey')
    op.drop_constraint('triage_records_user_id_fkey', 'triage_records', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('triage_records_user_id_fkey', 'triage_records', 'users', ['user_id'], ['id'])
    op.create_foreign_key('triage_records_patient_id_fkey', 'triage_records', 'patients', ['patient_id'], ['id'])
    op.alter_column('triage_records', 'brief',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('triage_records', 'transcript_odia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('triage_records', 'transcript_hindi',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('triage_records', 'transcript_english',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('triage_records', 'transcript',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.create_table('patients',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('village', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pregnant', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('abha_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='patients_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='patients_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('avatar_b64', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('banner_b64', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_employee_id', 'users', ['employee_id'], unique=True)
    op.create_table('symptom_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('primary_symptom', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('associated_symptoms', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('medication_taken', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('urgency_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('raw_transcript', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('call_sid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='symptom_reports_pkey')
    )
    op.create_index('ix_symptom_reports_id', 'symptom_reports', ['id'], unique=False)
    # ### end Alembic commands ###
